name: agravite
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.6.1
  gap: ^3.0.1
  google_fonts: ^6.2.1
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  bitsdojo_window: ^0.1.6
  flutter_svg: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  fonts:
    - family: Inter Variable
      fonts:
        - asset: assets/fonts/inter.ttf
        - asset: assets/fonts/inter_italic.ttf
          style: italic

  assets:
    - assets/svgs/Agravite.svg
